#include "ft_printf.h"
#include "limits.h"
#include <locale.h>
int main()
{
	// printf("%d\n", ft_printf("str*: %s\nint: %d\nchar: %c\ni: %i\n", "World", -2345, 'a', 50));
	// printf("%d\n", printf("str*: %s\nint: %d\nchar: %c\ni: %i\n", "World", -2345, 'a', 50));

	// ft_printf("u:%u", 184));
	// printf("%u", 184));
	// printf("%d\n", ft_printf("o:%o", 184));
	// printf("%d\n", printf("%o", 184));
	// printf("%d\n", ft_printf("x:%x", 184));
	// printf("%d\n", printf("%x", 184));
	// printf("%d\n", ft_printf("U:%U", 184));
	// printf("%d\n", printf("%U", 184));
	// printf("%d\n", ft_printf("O:%O", 184));
	// printf("%d\n", printf("%O", 184));
	// printf("%d\n", ft_printf("X:%X", 184));
	// printf("%d\n", printf("%X", 184));


	// ft_printf("%x\n", -42);
	// printf("%x", -42);

	// ft_printf("%p", &a);
	// printf("%s", "\n");
	// printf("%p", &a);

	// ft_printf("%o\n", -12);
	// printf("%o\n", -12);	

	// ft_printf("%O\n", 10000);
	// printf("%O", 10000);

	// ft_printf("%   %", "test");
	// //printf("%   %", "test");
	// ft_printf("%%%d\n", 1);
	// printf("%s", "\n");
	// printf("%%%d\n", 1);
	//printf("%%%d\n", 1);

	// ft_printf("%x", -42); 
	// printf("\n%x", -42); 
	// ft_printf("@moulitest: %s", NULL);
	// ft_printf("%u", -1);
	// printf("\n%u", -1);
	// ft_printf("%u", 4294967295);
	// printf("%u", 4294967295);

	// ft_printf("%U", 4294967295);
	// printf("\n%U", 4294967295);

	// ft_printf("%D", +9223372036854775807);
	//printf("\n%U", 4294967296);
	// int a;
	// wchar_t s[] = L"Привет Настя и пока";
	 setlocale(LC_ALL, "");
	// a = ft_printf("%S\n", s);
	// printf("%d\n", a);
	// printf("%d\n", printf("%S\n", s));

 //setlocale(LC_ALL, "");
 // if (MB_CUR_MAX == 1)
 // 	printf("%d\n", printf("%S\n", NULL));
	// // printf("%d\n", ft_printf("%S\n", NULL));
	// printf("aa%d\n", ft_printf("%S\n", L"рαα"));
	// printf("aa%d\n", printf("%S\n", L"рαα"));

	// printf("%d\n", ft_printf("αa%C\n", L'α'));
	// printf("%d\n", printf("αa%C\n", L'α'));
//if (MB_CUR_MAX == 4)
//	printf("%S\n", L"ααα");
	// printf("Heloo%%%s", "hello");
	// ft_printf("hello");
//	ft_printf("%s\n%s", "hello1", "hello2");
	// printf("%s\n", "hello");
	// ft_printf("%s\n", "hello");
	// char *s;
	// s = "Hello";
	// printf("%p\n", s);
	// ft_printf("%p\n", s);
	// printf("%o\n", 10);
	// ft_printf("%o\n", 10);
	// printf("c1: %lc\nx: %x\n", L'п', 5);
	// ft_printf("c2: %lc\nx: %x\n", L'п', 5);
//	printf("%s\n", "a"); ft_printf("%ls\n", "a");
	// printf("%ls\n", L"п");
	// printf("world %ls\n", L"hello");
	//  ft_printf("%ls\n", L"п");
	//  ft_printf("world %ls\n", L"hello");
	// printf("%ju\n", 4999999999);
	// // ft_printf("%ju\n", 4999999999);
	// printf("%d\n", ft_printf("%d %d %d %d gg!\n", 1, -2, 33, 42, 0));
	// printf("%d %d %d %d gg!\n", 1, -2, 33, 42, 0);
	// ft_printf("%jd\n", -9223372036854775808);
	// printf("%jd\n", -9223372036854775808);
	// printf("%d\n", ft_printf("null %c and text\n", 0));
	// printf("%d\n", printf("null %c and text\n", 0));
	// printf("%%\n");
	// printf("%d\n", ft_printf("%%\n"));
	// printf("%d\n", printf("%+d\n", -3));
	// printf("%d\n", ft_printf("%+d\n", -3));
	// printf("%d\n", printf("% d\n", -3));
	// printf("%d\n", ft_printf("% d\n", -3));
	// printf("%d\n", printf("% d\n", 3));
	// printf("%d\n", ft_printf("% d\n", 3));
	// printf("%d\n", printf("%+d\n", 3));
	// printf("%d\n", ft_printf("%+d\n", 3));
	// ft_printf("%hU", 4294967296); 
	// ft_printf("%#x", 0);
	// ft_printf("%-4d", 5);
	// printf("привет%ls\n", L"hello");
	// ft_printf("привет%ls\n", L"hello");
	// ft_printf("привет%-3ls\n", L"hello");
	// ft_printf("hello%S\n", L"привет");
	// printf("%d\n", printf("%-4hs\n", "привет"));
	// ft_printf("%-5%");
	//printf("%d\n", printf("%-10ls\n", L"привет"));
	// printf("%d\n", ft_printf("%-10S\n", L"привет"));
	// printf("%d\n", printf("%-10S\n", L"привет"));
	// ft_printf("%10s is a string\n", "this");
	// printf("%10s is a string\n", "this");
// ft_printf("%#6o", 2500);
	// printf("%d\n", printf("%07d\n", 8));
	// // printf("%d\n", ft_printf("%07d\n", 8));
	// printf("%+20d\n", 5);
	// ft_printf("%+20d\n", 5);
	// printf("{%s}", "");
	 // ft_printf("{%s}", "");
	// //printf("% Zoooo\n");
	// // // ft_printf("% Zoooo\n");
	// // printf("%d\n", printf("{%S}\n", NULL));
	// printf("%d\n", ft_printf("{%S}\n", NULL));
	// //printf("%O\n", LONG_MAX);
	// ft_printf("%O\n", LONG_MAX);
	//printf("%lD, %lD\n", 0, USHRT_MAX);
	// // ft_printf("%lD, %lD\n", 0, USHRT_MAX);
	// printf("%d\n", printf("%ho, %ho\n", 0, USHRT_MAX));
	// printf("%d\n", ft_printf("%ho, %ho\n", 0, USHRT_MAX));
	// ft_printf("%hho, %hho", 0, UCHAR_MAX);
	// printf("%hD, %hD\n", 0, USHRT_MAX);
	// // ft_printf("%hD, %hD", 0, USHRT_MAX);
	// printf("%hho, %hho\n", 0, UCHAR_MAX + 42);
	// ft_printf("%hho, %hho", 0, UCHAR_MAX + 42);
	// printf("%d\n", printf("{%10R}\n"));
	
	// printf("%d\n", ft_printf("{%10R}\n"));
	// // printf("% Zoooo\n");
	// // ft_printf("% Zoooo");
	// printf("%d\n", printf("before %d after\n", 42));
	// printf("%d\n", ft_printf("before %d after\n", 42));
	// printf("%+.4d\n", 5);
	// // // ft_printf("%+.4d\n", 5);
	// // printf("%.s", "0");
	// // ft_printf("%.s", "0");
	// printf("%d\n", printf("%4.2s\n", "123"));
	// printf("%d\n", ft_printf("%4.2s\n", "123"));
	// ft_printf("@moulitest: %.d %.0d", 0, 0);
	// ft_printf("%-5.2s is a string\n", "this");
	// printf("%-5.2s is a string\n", "this");
	 // ft_printf("@moulitest: %.10d", -42);
	// printf("{%-15Z}", 123);
	// ft_printf("%.4x\n", 42);
	// printf("%.4x\n", 42);
	// ft_printf("%03.2d", -1);
	// ft_printf("%c", 'a');
	//printf("%d\n", ft_printf("%c\n", L'я'));
	// printf("p: %d\n", printf("%04lc\n", L'п'));
	// // printf("f: %d\n", ft_printf("%04lc\n", L'п'));
	// printf("%d\n", printf("world %.4s\n", "hello"));
 //printf("%d\n", );
//	 printf("%d\n", ft_printf("world %.4s\n", "hello"));
	// printf("%d\n", printf("% Zoooo\n"));
	//printf("%d\n", ft_printf("% Zoooo\n"));
 // 	//printf("{%}\n");
 // printf("%d\n", ft_printf("{%}"));
 // printf("%d\n", printf("{%10R}\n"));
 // printf("%d\n", ft_printf("{%10R}\n"));
// printf("{%-10Z}\n", 123);
// ft_printf("{%-10Z}\n", 123);
// printf("{%010R}%.4s\n", "hello");
// ft_printf("{%010R}%.4s\n", "hello");
//ft_printf("{%-15Z\n}", 123);
//printf("{%-15Z\n}", 123);
	//ft_printf("%%%\n");
	// printf("%d\n", ft_printf("%"));
	// printf("%d\n", printf("{% 03d}\n", 0));
	// printf("%d\n", ft_printf("{% 03d}\n", 0));
	// ft_printf("%.4X", 42);
	// printf("%.C\n", 1);
	// ft_printf("%.C\n", 1);
	// char a;
	// printf("%.p, %.0p\n", a, a);
	// ft_printf("%.p, %.0p\n", a, a);
	// printf("%.5p", 0);
//	printf("% Zoooo\n");
	// ft_printf("% Zoooo");
	// ft_printf("%.5p", 0);
	//printf("{%05.s}\n", 0);
//	printf("{%05.s}\n", 0);
	// ft_printf("{%05.s}\n", 0);
	// printf("{%05.Z}\n", 0);
	// ft_printf("{%05.Z}\n", 0);
	//printf("{%5.s}\n", 0);
	//printf("{%#.5x}\n", 1);
	//printf("%#x", 0);
	// ft_printf("{%#.5x}\n", 1);
	// //ft_printf("%#x", 0);
	// ft_printf("{%#.5x}\n", 1);
	// printf("%#o\n", 0);
	// ft_printf("%#o\n", 0);
	// printf("%#.3o", 1);
	// ft_printf("%#.3o\n", 1);
	// printf("{%05.S}\n", L"42 c est cool");
	// // ft_printf("{%05.S}\n", L"42 c est cool");
	// printf("{%#.5x}", 1);
	// ft_printf("{%#.5x}\n", 1);
	// //printf("%.4S", L"ÊM-M-^QÊM-^XØ‰∏M-ÂM-^O™ÁM-^L´„M-M-^B");
	ft_printf("%.4S\n", L"Привет");
	printf("%.4S\n", L"Привет");
 // printf("%d\n", printf("p: %.4S\n", L"ÊM-M-^QÊM-^XØ‰∏M-ÂM-^O™ÁM-^L´„M-M-^B"));
 // printf("%d\n", ft_printf("f: %.4S\n", L"ÊM-M-^QÊM-^XØ‰∏M-ÂM-^O™ÁM-^L´„M-M-^B"));
	return (0);
}
